# Generated by Django 3.1.7 on 2021-02-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=25)),
                ('start_yr', models.CharField(max_length=25)),
                ('end_yr', models.CharField(max_length=25)),
                ('institute', models.CharField(max_length=25)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
