# Generated by Django 3.1.7 on 2021-02-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0003_auto_20210227_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='workModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=88)),
                ('title', models.CharField(max_length=88)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
