# Generated by Django 3.1.7 on 2021-02-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0007_extramodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='proModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=80)),
                ('industrial', models.CharField(max_length=80)),
                ('projlink', models.URLField(blank=True)),
            ],
        ),
    ]
