# Generated by Django 3.1.7 on 2021-02-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0008_promodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promodel',
            name='projlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
