# Generated by Django 3.1.7 on 2021-03-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0009_auto_20210227_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posmodel',
            name='first',
            field=models.CharField(max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='handle',
            field=models.CharField(max_length=250),
        ),
    ]
