# Generated by Django 3.1.7 on 2021-03-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0010_auto_20210304_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posmodel',
            name='last',
            field=models.CharField(max_length=88, null=True),
        ),
    ]
