# Generated by Django 3.1.7 on 2021-03-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0012_auto_20210304_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=250)),
            ],
        ),
    ]
