# Generated by Django 3.1.7 on 2021-03-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0013_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posmodel',
            name='first',
            field=models.CharField(default='Empty', max_length=88),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='handle',
            field=models.CharField(default='Empty', max_length=250),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='last',
            field=models.CharField(default='Empty', max_length=88),
        ),
    ]
