# Generated by Django 3.1.7 on 2021-03-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0014_auto_20210306_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posmodel',
            name='first',
            field=models.CharField(blank=True, default='Empty', max_length=88, null=True),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='handle',
            field=models.CharField(blank=True, default='Empty', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='posmodel',
            name='last',
            field=models.CharField(blank=True, default='Empty', max_length=88, null=True),
        ),
    ]
