# Generated by Django 3.1.1 on 2021-03-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0018_auto_20210227_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('Pursuing', 'Pursuing'), ('Completed', 'Completed')], default='Completed', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('High School', 'High School')], max_length=25),
        ),
    ]
