# Generated by Django 3.1.1 on 2021-03-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0019_auto_20210308_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Masters', 'Masters'), ('Bachelors', 'Bachelors'), ('High School', 'High School')], max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('Pursuing', 'Pursuing'), ('Completed', 'Completed')], max_length=25, unique=True),
        ),
    ]
