# Generated by Django 3.1.1 on 2021-03-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0022_auto_20210312_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='left_dt',
            field=models.DateField(null=True),
        ),
    ]
