# Generated by Django 3.1.1 on 2021-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0024_auto_20210313_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
