# Generated by Django 3.1.7 on 2021-03-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0017_auto_20210307_0907'),
        ('resume_maker', '0027_auto_20210314_1400'),
    ]

    operations = [
    ]
