# Generated by Django 3.1.7 on 2021-03-16 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_maker', '0028_merge_20210315_2210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acaModel',
        ),
        migrations.DeleteModel(
            name='additional',
        ),
        migrations.DeleteModel(
            name='EducatModel',
        ),
        migrations.DeleteModel(
            name='extraModel',
        ),
        migrations.DeleteModel(
            name='posModel',
        ),
        migrations.DeleteModel(
            name='proModel',
        ),
        migrations.DeleteModel(
            name='workModel',
        ),
    ]
